// Vocabulary bo'limi uchun ma'lumotlar bazasi.
// 20 ta biznes mavzusi, har birida 30 tadan so'z, A1 dan C2 gacha (har darajada 5 tadan).
// Mavzular Speaking bo'limidagi asosiy biznes mavzulariga mos tanlangan.

export const VOCAB_TOPICS = [
  { id: "job_interviews", icon: "🧑‍💼", name: "Ish suhbati" },
  { id: "meetings", icon: "🗓", name: "Yig'ilishlar" },
  { id: "negotiations", icon: "🤝", name: "Muzokaralar" },
  { id: "presentations", icon: "📊", name: "Taqdimotlar" },
  { id: "emails", icon: "📧", name: "Elektron yozishmalar" },
  { id: "marketing", icon: "📣", name: "Marketing" },
  { id: "sales", icon: "💰", name: "Sotuv" },
  { id: "finance", icon: "🏦", name: "Moliya" },
  { id: "hr", icon: "👥", name: "Kadrlar boshqaruvi" },
  { id: "management", icon: "🧭", name: "Boshqaruv va liderlik" },
  { id: "customer_service", icon: "🎧", name: "Mijozlarga xizmat" },
  { id: "business_travel", icon: "✈️", name: "Ish safarlari" },
  { id: "networking", icon: "🌐", name: "Aloqalar o'rnatish" },
  { id: "startups", icon: "🚀", name: "Startaplar" },
  { id: "logistics", icon: "📦", name: "Ta'minot va logistika" },
  { id: "technology", icon: "💻", name: "Texnologiya va IT" },
  { id: "project_management", icon: "📋", name: "Loyiha boshqaruvi" },
  { id: "legal", icon: "⚖️", name: "Huquq va shartnomalar" },
  { id: "strategy", icon: "♟", name: "Strategiya" },
  { id: "workplace_culture", icon: "🏢", name: "Ofis madaniyati" },
];

// Har bir mavzu uchun: [level, term, uz, def, example]
const RAW = {
  job_interviews: [
    ["A1", "job", "ish", "Work that a person does to earn money.", "She has a new job at a bank."],
    ["A1", "interview", "suhbat (ishga)", "A formal meeting to see if someone is right for a job.", "The interview is at 2 PM tomorrow."],
    ["A1", "CV", "rezyume", "A document listing a person's education and work experience.", "Please send your CV by email."],
    ["A1", "salary", "maosh", "The fixed money paid to an employee regularly.", "The salary is paid at the end of the month."],
    ["A1", "skill", "ko'nikma", "The ability to do something well.", "Communication is an important skill."],
    ["A2", "candidate", "nomzod", "A person who applies for a job.", "There were ten candidates for the position."],
    ["A2", "employer", "ish beruvchi", "A person or company that hires workers.", "Her employer gave her a promotion."],
    ["A2", "experience", "tajriba", "Knowledge gained from doing a job over time.", "He has five years of experience in sales."],
    ["A2", "apply", "ariza bermoq", "To formally request a job.", "I applied for the marketing position."],
    ["A2", "qualification", "malaka", "A skill or achievement that makes someone suitable for a job.", "A degree in finance is a required qualification."],
    ["B1", "recruitment", "yollash jarayoni", "The process of finding and hiring new employees.", "The recruitment process takes about a month."],
    ["B1", "shortlist", "tanlangan nomzodlar ro'yxati", "A small list of the best candidates chosen from a larger group.", "She was placed on the shortlist for the manager role."],
    ["B1", "reference", "tavsiyanoma", "A statement from a previous employer about a person's work.", "He asked his old boss for a reference."],
    ["B1", "probation period", "sinov muddati", "A trial period at the start of a job.", "The probation period lasts three months."],
    ["B1", "strength", "kuchli tomon", "A skill or quality a person is good at.", "Teamwork is one of her strengths."],
    ["B2", "candidate pool", "nomzodlar havzasi", "The full group of people applying for a job.", "The candidate pool was larger than expected."],
    ["B2", "competency-based interview", "kompetensiyaga asoslangan suhbat", "An interview focused on past examples of specific skills.", "He prepared examples for the competency-based interview."],
    ["B2", "notice period", "ogohlantirish muddati", "The time an employee must work after resigning before leaving.", "Her notice period is two weeks."],
    ["B2", "career objective", "kasbiy maqsad", "A statement of a person's professional goals.", "His career objective is to become a team leader."],
    ["B2", "panel interview", "hay'at bilan suhbat", "An interview conducted by several interviewers at once.", "The panel interview included three senior managers."],
    ["C1", "headhunter", "kadr izlovchi", "A person who finds skilled people for companies to hire.", "A headhunter contacted her about a new role."],
    ["C1", "onboarding", "moslashuv jarayoni", "The process of integrating a new employee into a company.", "The onboarding program lasts two weeks."],
    ["C1", "talent acquisition", "iqtidor jalb qilish", "The strategic process of finding and hiring skilled people.", "Talent acquisition is a key HR function."],
    ["C1", "succession planning", "vorislik rejasi", "Planning who will take over key roles in the future.", "Succession planning ensures leadership continuity."],
    ["C1", "counteroffer", "qarshi taklif", "An improved offer made to keep an employee from leaving.", "The company made a counteroffer to retain him."],
    ["C2", "psychometric assessment", "psixometrik baholash", "A test measuring mental capabilities and behavioral style.", "Candidates completed a psychometric assessment online."],
    ["C2", "executive search", "yuqori lavozim izlash", "A specialized recruitment service for senior positions.", "The firm used executive search to hire a new CEO."],
    ["C2", "tenure", "lavozimda ishlash muddati", "The length of time a person holds a position.", "Her tenure as director lasted eight years."],
    ["C2", "attrition", "xodimlar chiqib ketishi", "The gradual loss of employees over time.", "High attrition is a concern for the HR team."],
    ["C2", "meritocracy", "meritokratiya", "A system where advancement is based on ability, not status.", "The company prides itself on being a meritocracy."],
  ],
  meetings: [
    ["A1", "meeting", "yig'ilish", "A planned gathering of people to discuss something.", "We have a meeting at 10 AM."],
    ["A1", "agenda", "kun tartibi", "A list of topics to be discussed in a meeting.", "Please check the agenda before the meeting."],
    ["A1", "room", "xona", "A space where a meeting takes place.", "The meeting is in room 302."],
    ["A1", "chair", "rahbarlik qiluvchi", "The person who leads a meeting.", "She will chair today's meeting."],
    ["A1", "start", "boshlamoq", "To begin an activity.", "The meeting will start at nine."],
    ["A2", "attend", "qatnashmoq", "To be present at an event.", "All managers must attend the meeting."],
    ["A2", "schedule", "jadval", "A plan of when things will happen.", "Let's schedule the meeting for Monday."],
    ["A2", "discuss", "muhokama qilmoq", "To talk about a topic in detail.", "We need to discuss the new budget."],
    ["A2", "postpone", "kechiktirmoq", "To delay an event to a later time.", "The meeting was postponed until next week."],
    ["A2", "decision", "qaror", "A choice made after consideration.", "We made a final decision today."],
    ["B1", "brainstorm", "fikrlar to'plash", "To generate many ideas quickly as a group.", "Let's brainstorm some solutions."],
    ["B1", "action point", "harakat rejasi bandi", "A specific task agreed upon during a meeting.", "Each action point has a deadline."],
    ["B1", "follow-up", "keyingi qadam", "A subsequent action or meeting after the initial one.", "We'll send a follow-up email tomorrow."],
    ["B1", "consensus", "kelishuv", "General agreement among a group.", "The team reached a consensus quickly."],
    ["B1", "deadline", "muddat", "The latest time by which something must be done.", "The deadline for the report is Friday."],
    ["B2", "stakeholder", "manfaatdor tomon", "A person with an interest in the outcome of a decision.", "All key stakeholders attended the meeting."],
    ["B2", "videoconference", "video konferensiya", "A meeting held remotely using video technology.", "We held a videoconference with the Tokyo office."],
    ["B2", "facilitator", "yo'naltiruvchi", "A person who helps a meeting run smoothly.", "The facilitator kept the discussion on track."],
    ["B2", "off-topic", "mavzudan chetga chiqish", "Not related to the main subject being discussed.", "Please avoid off-topic comments."],
    ["B2", "quorum", "kvorum", "The minimum number of people needed to make decisions valid.", "We didn't have a quorum, so voting was postponed."],
    ["C1", "agenda item", "kun tartibi bandi", "A single topic listed for discussion in a meeting.", "The budget was the first agenda item."],
    ["C1", "roundtable", "davra suhbati", "An informal discussion where everyone has equal say.", "The CEOs joined a roundtable discussion."],
    ["C1", "groupthink", "guruh fikri", "The tendency to conform to group opinion without critical thinking.", "Groupthink led to a poor decision."],
    ["C1", "digression", "chetga chiqish", "A temporary departure from the main topic.", "His digression wasted valuable meeting time."],
    ["C1", "adjourn", "yig'ilishni yakunlamoq", "To formally end or pause a meeting.", "The chair adjourned the meeting at noon."],
    ["C2", "parliamentary procedure", "parlament tartib-qoidasi", "Formal rules governing how meetings are conducted.", "The board follows strict parliamentary procedure."],
    ["C2", "tacit agreement", "aytilmagan kelishuv", "An unspoken but understood agreement.", "There was a tacit agreement not to raise the issue."],
    ["C2", "deliberation", "chuqur muhokama", "Careful discussion before reaching a decision.", "After lengthy deliberation, the board approved the plan."],
    ["C2", "plenary session", "umumiy majlis", "A meeting attended by all members of an organization.", "The plenary session opened the conference."],
    ["C2", "minute-taking", "bayonnoma yuritish", "The act of recording what happens in a meeting.", "She is responsible for minute-taking today."],
  ],
  negotiations: [
    ["A1", "price", "narx", "The amount of money needed to buy something.", "What is the price of this product?"],
    ["A1", "deal", "kelishuv", "An agreement between two parties.", "We made a good deal."],
    ["A1", "offer", "taklif", "An amount of money someone is willing to pay or accept.", "They made an offer for the house."],
    ["A1", "agree", "kelishmoq", "To have the same opinion or accept a proposal.", "Both sides agreed on the price."],
    ["A1", "discount", "chegirma", "A reduction in the usual price.", "We got a 10% discount."],
    ["A2", "negotiate", "muzokara olib bormoq", "To discuss something to reach an agreement.", "They negotiated a better price with the supplier."],
    ["A2", "bargain", "savdolashmoq", "To discuss a price until both sides agree.", "He bargained for a lower price."],
    ["A2", "contract", "shartnoma", "A written legal agreement.", "They signed the contract yesterday."],
    ["A2", "terms", "shartlar", "The conditions of an agreement.", "The terms of the deal were fair."],
    ["A2", "propose", "taklif qilmoq", "To formally suggest something.", "She proposed a new payment plan."],
    ["B1", "counteroffer", "qarshi taklif", "A new offer made in response to a rejected one.", "The buyer made a counteroffer."],
    ["B1", "compromise", "murosaga kelish", "An agreement reached by each side giving up something.", "Both sides reached a compromise after long talks."],
    ["B1", "leverage", "afzallik", "An advantage that gives someone more power in negotiation.", "Their market position gave them leverage."],
    ["B1", "concession", "yon berish", "Something given up in a negotiation to reach agreement.", "Neither party was willing to make a concession."],
    ["B1", "deadlock", "tanglik holati", "A situation where no agreement can be reached.", "The talks ended in a deadlock."],
    ["B2", "win-win", "ikki tomon ham yutadigan", "A situation beneficial to both parties.", "They aimed for a win-win outcome."],
    ["B2", "walk away", "muzokaradan chiqib ketmoq", "To leave a negotiation without an agreement.", "She was ready to walk away from the deal."],
    ["B2", "bottom line", "eng past chegara", "The minimum acceptable outcome in a negotiation.", "Our bottom line is $50,000."],
    ["B2", "mediator", "vositachi", "A neutral person who helps parties reach agreement.", "A mediator was brought in to resolve the dispute."],
    ["B2", "breakthrough", "yutuq (muzokarada)", "A sudden important development that ends a deadlock.", "They finally reached a breakthrough in talks."],
    ["C1", "zero-sum game", "nol summali o'yin", "A situation where one side's gain is another's loss.", "The negotiation felt like a zero-sum game."],
    ["C1", "impasse", "tiqilinch holat", "A point where no progress is possible.", "Talks reached an impasse over pricing."],
    ["C1", "arbitration", "arbitraj", "Formal resolution of a dispute by a neutral third party.", "The dispute went to arbitration."],
    ["C1", "brinkmanship", "xavf yoqasida turish taktikasi", "Pushing a dangerous situation to the limit to gain advantage.", "His brinkmanship nearly collapsed the deal."],
    ["C1", "stalling tactic", "vaqt cho'zish taktikasi", "A strategy of delaying to gain advantage.", "They used a stalling tactic to gather more information."],
    ["C2", "anchoring", "boshlang'ich narx belgilash taktikasi", "Setting an initial offer to influence the final outcome.", "The seller used anchoring by starting with a high price."],
    ["C2", "reciprocity", "o'zaro almashinuv printsipi", "The practice of exchanging favorable actions with others.", "Reciprocity is a key principle in negotiation."],
    ["C2", "good faith", "halol niyat", "Sincere intention to negotiate honestly.", "Both sides negotiated in good faith."],
    ["C2", "ratification", "tasdiqlash", "Formal approval of an agreement.", "The contract awaits ratification by the board."],
    ["C2", "coercive tactics", "majburlash taktikasi", "Pressure-based strategies used to force agreement.", "The union rejected the coercive tactics of management."],
  ],
  presentations: [
    ["A1", "slide", "slayd", "A single page of a presentation shown on screen.", "The first slide shows the title."],
    ["A1", "screen", "ekran", "A surface where images or slides are displayed.", "Look at the screen, please."],
    ["A1", "speak", "gapirmoq", "To talk or say words aloud.", "She will speak for ten minutes."],
    ["A1", "audience", "tinglovchilar", "The group of people watching a presentation.", "The audience asked many questions."],
    ["A1", "topic", "mavzu", "The subject being discussed.", "The topic today is marketing."],
    ["A2", "presentation", "taqdimot", "A talk given to explain or show something.", "He gave a great presentation."],
    ["A2", "introduce", "tanishtirmoq", "To present something or someone for the first time.", "Let me introduce our new product."],
    ["A2", "explain", "tushuntirmoq", "To make something clear by describing it.", "She explained the results clearly."],
    ["A2", "summarize", "xulosa qilmoq", "To give a brief statement of main points.", "Let's summarize the key ideas."],
    ["A2", "question", "savol", "A sentence asked to get information.", "Does anyone have a question?"],
    ["B1", "visual aid", "vizual vosita", "An image, chart, or object used to help explain ideas.", "The chart was a helpful visual aid."],
    ["B1", "main point", "asosiy fikr", "The most important idea being communicated.", "The main point is cost reduction."],
    ["B1", "handout", "tarqatma material", "A printed document given to an audience.", "Please take a handout as you leave."],
    ["B1", "rehearse", "mashq qilmoq", "To practice a presentation before delivering it.", "He rehearsed his speech twice."],
    ["B1", "feedback", "fikr-mulohaza", "Comments given about performance or work.", "The feedback was mostly positive."],
    ["B2", "engage the audience", "tinglovchilarni jalb qilish", "To keep listeners interested and involved.", "She used stories to engage the audience."],
    ["B2", "body language", "tana tili", "Communication through gestures and posture.", "His confident body language impressed everyone."],
    ["B2", "key takeaway", "asosiy xulosa", "The most important message the audience should remember.", "The key takeaway was to act quickly."],
    ["B2", "rhetorical question", "ritorik savol", "A question asked for effect, not requiring an answer.", "He opened with a rhetorical question."],
    ["B2", "pace", "sur'at", "The speed at which a presentation is delivered.", "Keep a steady pace when speaking."],
    ["C1", "persuasive techniques", "ishontirish usullari", "Methods used to convince an audience.", "The speaker used several persuasive techniques."],
    ["C1", "narrative arc", "hikoya chizig'i", "The structure of a story used to build interest.", "The presentation followed a clear narrative arc."],
    ["C1", "Q&A session", "savol-javob qismi", "A part of a talk for audience questions.", "The Q&A session lasted fifteen minutes."],
    ["C1", "filler words", "to'ldiruvchi so'zlar", "Unnecessary words used while pausing, like 'um' or 'like'.", "Try to avoid filler words during your talk."],
    ["C1", "call to action", "harakatga chaqiruv", "A statement urging the audience to take a specific action.", "The presentation ended with a strong call to action."],
    ["C2", "audience segmentation", "tinglovchilarni segmentlash", "Dividing an audience into groups for tailored messaging.", "Audience segmentation shaped the presentation's tone."],
    ["C2", "storytelling framework", "hikoya qurilishi tizimi", "A structured approach to telling a compelling story.", "He built his pitch on a storytelling framework."],
    ["C2", "cognitive load", "kognitiv yuk", "The amount of mental effort needed to process information.", "Too much text increases cognitive load."],
    ["C2", "delivery style", "taqdim etish uslubi", "The manner in which a speaker presents information.", "Her delivery style was calm and authoritative."],
    ["C2", "impromptu speech", "tayyorgarliksiz nutq", "A speech given without prior preparation.", "He handled the impromptu speech with confidence."],
  ],
  emails: [
    ["A1", "email", "elektron xat", "A message sent electronically.", "I sent you an email yesterday."],
    ["A1", "send", "yubormoq", "To make something go to a recipient.", "Please send the file today."],
    ["A1", "reply", "javob bermoq", "To respond to a message.", "She will reply tomorrow."],
    ["A1", "attach", "ilova qilmoq", "To include a file with a message.", "I attached the document."],
    ["A1", "subject", "mavzu qatori", "The topic line of an email.", "The subject says 'Meeting Update'."],
    ["A2", "inbox", "kiruvchi xatlar qutisi", "The folder where received emails appear.", "My inbox is full of messages."],
    ["A2", "forward", "boshqaga yubormoq", "To send a received message to someone else.", "Can you forward this email to the team?"],
    ["A2", "cc", "nusxa yuborish", "To send a copy of an email to another person.", "Please cc me on that email."],
    ["A2", "signature", "imzo (elektron xatda)", "The block of text at the end of an email with sender's details.", "His email signature includes his phone number."],
    ["A2", "draft", "qoralama", "An unfinished or unsent version of a message.", "I saved the email as a draft."],
    ["B1", "follow up", "kuzatib bormoq", "To send a reminder or additional message.", "I'll follow up next week."],
    ["B1", "formal tone", "rasmiy ohang", "A professional and polite writing style.", "Business emails should have a formal tone."],
    ["B1", "greeting", "salomlashish", "The opening words of an email, e.g. 'Dear Sir'.", "Start with a polite greeting."],
    ["B1", "closing remark", "yakuniy jumla", "The final sentence before signing off.", "He ended with a friendly closing remark."],
    ["B1", "urgent", "shoshilinch", "Requiring immediate attention.", "This matter is urgent, please respond soon."],
    ["B2", "cold email", "notanish shaxsga yozilgan xat", "An email sent to someone with no prior contact.", "She sent a cold email to a potential client."],
    ["B2", "out of office", "ofisdan tashqarida", "An automatic reply sent when someone is unavailable.", "I set up an out of office reply."],
    ["B2", "bcc", "yashirin nusxa", "To send a hidden copy of an email to someone.", "He bcc'd his manager on the email."],
    ["B2", "disclaimer", "ogohlantirish matni", "A statement limiting legal responsibility, often at the email's end.", "The email included a confidentiality disclaimer."],
    ["B2", "thread", "yozishma zanjiri", "A series of connected emails on the same topic.", "Please check the full email thread."],
    ["C1", "boilerplate", "standart matn", "Standard text reused in many emails or documents.", "The contract clause was boilerplate language."],
    ["C1", "correspondence etiquette", "yozishma odobi", "The accepted norms of professional writing.", "Good correspondence etiquette builds trust."],
    ["C1", "escalate", "yuqori darajaga ko'tarmoq", "To pass an issue to someone with more authority.", "I had to escalate the complaint to my manager."],
    ["C1", "courtesy copy", "hurmat nusxasi", "A copy of an email sent as a courtesy, not for action.", "She was added as a courtesy copy."],
    ["C1", "read receipt", "o'qilganlik tasdig'i", "A notification confirming an email was opened.", "He requested a read receipt for the contract."],
    ["C2", "tacit acknowledgment", "sukut bilan tan olish", "An implied agreement without direct confirmation.", "His silence was a tacit acknowledgment of the error."],
    ["C2", "terse reply", "qisqa va quruq javob", "A brief and somewhat curt response.", "Her terse reply suggested she was annoyed."],
    ["C2", "diplomatic phrasing", "diplomatik ifoda", "Careful wording used to avoid offense.", "He used diplomatic phrasing to reject the proposal."],
    ["C2", "canned response", "tayyor javob", "A pre-written reply used for common situations.", "Customer service sent a canned response."],
    ["C2", "deferred reply", "kechiktirilgan javob", "A response postponed to a later time.", "She gave a deferred reply pending approval."],
  ],
  marketing: [
    ["A1", "brand", "brend", "The name or identity of a product or company.", "This is a famous brand."],
    ["A1", "ad", "reklama", "A short form of advertisement.", "I saw an ad on TV."],
    ["A1", "product", "mahsulot", "Something made or offered for sale.", "The new product is popular."],
    ["A1", "price", "narx", "The cost of something.", "The price is very reasonable."],
    ["A1", "customer", "mijoz", "A person who buys goods or services.", "The customer was happy with the service."],
    ["A2", "advertise", "reklama qilmoq", "To promote a product publicly.", "They advertise on social media."],
    ["A2", "campaign", "kampaniya", "A series of planned marketing activities.", "The campaign starts next month."],
    ["A2", "market", "bozor", "The group of people who might buy a product.", "They entered a new market."],
    ["A2", "promote", "targ'ib qilmoq", "To help sell something by advertising it.", "We promote our app on Instagram."],
    ["A2", "logo", "logotip", "A symbol representing a company or brand.", "The logo appears on all packaging."],
    ["B1", "target market", "maqsadli bozor", "The specific group a product is aimed at.", "Our target market is young professionals."],
    ["B1", "market research", "bozor tadqiqoti", "The study of customer needs and market trends.", "Market research showed strong demand."],
    ["B1", "slogan", "shior", "A short memorable marketing phrase.", "The company's slogan is catchy."],
    ["B1", "packaging", "qadoqlash", "The material used to wrap or contain a product.", "The packaging is eco-friendly."],
    ["B1", "competitor", "raqib", "A company selling similar products.", "Our main competitor lowered its prices."],
    ["B2", "brand awareness", "brend tanilganligi", "How familiar the public is with a brand.", "The ad campaign increased brand awareness."],
    ["B2", "market segmentation", "bozorni segmentlash", "Dividing a market into groups of similar customers.", "Market segmentation helped target the right buyers."],
    ["B2", "positioning", "pozitsiyalash", "How a brand is perceived relative to competitors.", "The brand's positioning focuses on luxury."],
    ["B2", "viral campaign", "viral kampaniya", "A campaign that spreads quickly through sharing.", "The viral campaign reached millions of viewers."],
    ["B2", "call to action", "harakatga chaqiruv", "A prompt encouraging the audience to act.", "The ad ends with a strong call to action."],
    ["C1", "brand equity", "brend qiymati", "The value a brand adds beyond its product.", "Strong brand equity allows premium pricing."],
    ["C1", "niche market", "tor bozor", "A small, specialized segment of a market.", "They focus on a niche market of eco-products."],
    ["C1", "market penetration", "bozorga kirib borish", "The extent to which a product is sold in a market.", "Market penetration increased after the discount campaign."],
    ["C1", "influencer marketing", "influenser marketingi", "Promoting products through popular social media figures.", "Influencer marketing boosted brand visibility."],
    ["C1", "customer journey", "mijoz yo'li", "The full experience a customer has with a brand.", "They mapped the entire customer journey."],
    ["C2", "brand cannibalization", "brendni yeb qo'yish effekti", "When a new product reduces sales of an existing one.", "The new model caused brand cannibalization."],
    ["C2", "psychographics", "psixografika", "Data on consumer attitudes, values, and lifestyles.", "Psychographics helped refine the ad's message."],
    ["C2", "first-mover advantage", "birinchi bo'lish afzalligi", "The benefit gained by being first in a market.", "They enjoyed a first-mover advantage in the region."],
    ["C2", "market saturation", "bozor to'yinganligi", "The point where a market can absorb no more of a product.", "Market saturation forced them to look abroad."],
    ["C2", "guerrilla marketing", "partizan marketingi", "Unconventional, low-cost marketing tactics.", "The startup used guerrilla marketing to save costs."],
  ],
  sales: [
    ["A1", "sell", "sotmoq", "To exchange goods for money.", "They sell fresh bread."],
    ["A1", "buy", "sotib olmoq", "To obtain something by paying money.", "I want to buy a new phone."],
    ["A1", "order", "buyurtma", "A request to purchase goods.", "I placed an order online."],
    ["A1", "shop", "do'kon", "A place where goods are sold.", "The shop opens at nine."],
    ["A1", "receipt", "chek", "A document proving payment.", "Keep your receipt for a refund."],
    ["A2", "discount", "chegirma", "A reduction in price.", "We offer a 20% discount today."],
    ["A2", "customer", "mijoz", "A person who buys goods or services.", "The customer left a good review."],
    ["A2", "deal", "kelishuv", "An agreement to buy or sell something.", "We closed the deal yesterday."],
    ["A2", "offer", "taklif", "A proposed price or arrangement.", "They made a special offer."],
    ["A2", "purchase", "xarid", "The act of buying something.", "Thank you for your purchase."],
    ["B1", "sales pitch", "sotuv nutqi", "A persuasive talk to sell a product.", "He gave a confident sales pitch."],
    ["B1", "quota", "reja (sotuv)", "A target number of sales to achieve.", "She exceeded her monthly quota."],
    ["B1", "commission", "komissiya", "Payment based on the amount sold.", "Salespeople earn a commission on each sale."],
    ["B1", "upsell", "qo'shimcha sotuv", "To persuade a customer to buy something more expensive.", "The waiter tried to upsell a dessert."],
    ["B1", "close a deal", "bitimni yakunlamoq", "To successfully complete a sale.", "It took weeks to close the deal."],
    ["B2", "sales funnel", "sotuv voronkasi", "The stages a customer goes through before buying.", "Most leads drop out early in the sales funnel."],
    ["B2", "lead generation", "potensial mijoz topish", "The process of attracting potential customers.", "Social media boosted our lead generation."],
    ["B2", "cold calling", "notanish mijozga qo'ng'iroq", "Calling potential customers with no prior contact.", "Cold calling is still used in B2B sales."],
    ["B2", "conversion rate", "konversiya darajasi", "The percentage of leads that become customers.", "The conversion rate improved after the redesign."],
    ["B2", "follow-up call", "keyingi qo'ng'iroq", "A call made after initial contact to move a sale forward.", "She scheduled a follow-up call for Monday."],
    ["C1", "cross-sell", "qo'shimcha mahsulot sotish", "To sell a related product to an existing customer.", "The bank tried to cross-sell insurance products."],
    ["C1", "churn rate", "mijozlar yo'qotish darajasi", "The rate at which customers stop using a service.", "High churn rate hurt subscription revenue."],
    ["C1", "sales cycle", "sotuv sikli", "The full process from first contact to closing a sale.", "The sales cycle for enterprise clients is long."],
    ["C1", "prospecting", "potensial mijoz izlash", "Searching for new potential customers.", "Prospecting takes up much of a salesperson's time."],
    ["C1", "objection handling", "e'tirozlarga javob berish", "Responding effectively to a customer's concerns.", "Good objection handling can save a sale."],
    ["C2", "pipeline forecasting", "sotuv oqimini bashorat qilish", "Predicting future sales based on the current pipeline.", "Pipeline forecasting guides quarterly targets."],
    ["C2", "customer lifetime value", "mijozning umrbod qiymati", "The total revenue expected from a customer over time.", "They calculated customer lifetime value carefully."],
    ["C2", "sales enablement", "sotuvni qo'llab-quvvatlash", "Providing sales teams with tools and content to sell better.", "Sales enablement improved the team's performance."],
    ["C2", "gatekeeper", "darvozabon", "A person who controls access to a decision maker.", "The receptionist acted as a gatekeeper."],
    ["C2", "account-based selling", "hisobga asoslangan sotuv", "A strategy targeting specific high-value accounts.", "They shifted to account-based selling for large clients."],
  ],
  finance: [
    ["A1", "money", "pul", "Currency used to buy things.", "He doesn't have much money."],
    ["A1", "bank", "bank", "A place where money is kept and managed.", "I opened an account at the bank."],
    ["A1", "pay", "to'lamoq", "To give money for something.", "I need to pay the bill."],
    ["A1", "cash", "naqd pul", "Money in the form of coins or notes.", "Do you accept cash?"],
    ["A1", "price", "narx", "The cost of something.", "The price went up."],
    ["A2", "account", "hisob raqami", "A record held at a bank for managing money.", "She checked her bank account."],
    ["A2", "save", "jamg'armoq", "To keep money for future use.", "They save money every month."],
    ["A2", "budget", "byudjet", "A plan for how money will be spent.", "We need to stay within budget."],
    ["A2", "loan", "kredit", "Money borrowed that must be paid back.", "He took out a loan to buy a car."],
    ["A2", "income", "daromad", "Money received regularly, especially from work.", "Her income increased this year."],
    ["B1", "interest rate", "foiz stavkasi", "The percentage charged on borrowed money.", "The interest rate rose last month."],
    ["B1", "expense", "xarajat", "Money spent on something.", "Travel expenses are covered by the company."],
    ["B1", "profit", "foyda", "Money gained after costs are subtracted.", "The company made a large profit."],
    ["B1", "invoice", "hisob-faktura", "A document listing goods sold and money owed.", "Please send the invoice by Friday."],
    ["B1", "tax", "soliq", "Money paid to the government.", "Income tax is deducted from the salary."],
    ["B2", "revenue", "daromad (kompaniya)", "The total income generated by a business.", "Revenue increased by 15% last year."],
    ["B2", "cash flow", "pul oqimi", "The movement of money into and out of a business.", "Positive cash flow keeps a business healthy."],
    ["B2", "asset", "aktiv", "Something valuable that a company or person owns.", "Real estate is a major asset."],
    ["B2", "liability", "majburiyat (moliyaviy)", "A debt or financial obligation.", "The company reduced its liabilities."],
    ["B2", "investment", "investitsiya", "Money put into something to earn a return.", "They made a wise investment in stocks."],
    ["C1", "liquidity", "likvidlik", "The availability of liquid assets to a company or market.", "The bank ensured sufficient liquidity."],
    ["C1", "equity", "kapital ulushi", "Ownership value in a company after debts are subtracted.", "Investors received equity in the startup."],
    ["C1", "dividend", "dividend", "A payment made to shareholders from company profits.", "The company paid a quarterly dividend."],
    ["C1", "depreciation", "amortizatsiya", "The decrease in value of an asset over time.", "Depreciation is calculated annually."],
    ["C1", "capital gain", "kapital foydasi", "Profit from selling an asset for more than its cost.", "She reported a capital gain on the sale."],
    ["C2", "amortization", "qarzni bosqichma-bosqich to'lash", "Gradually paying off a debt or asset cost over time.", "The loan has a 10-year amortization schedule."],
    ["C2", "arbitrage", "arbitraj (moliyaviy)", "Profiting from price differences in different markets.", "The trader used arbitrage to earn quick profits."],
    ["C2", "derivative", "hosila moliyaviy vosita", "A financial contract whose value depends on an asset.", "The fund invested in complex derivatives."],
    ["C2", "insolvency", "to'lovga qobiliyatsizlik", "The state of being unable to pay debts.", "The company filed for insolvency."],
    ["C2", "hedge fund", "xedj-fond", "An investment fund using high-risk strategies for high returns.", "The hedge fund reported strong annual returns."],
  ],
  hr: [
    ["A1", "staff", "xodimlar", "The people who work for an organization.", "The staff meeting is at noon."],
    ["A1", "hire", "yollamoq", "To employ someone.", "We plan to hire three new workers."],
    ["A1", "work", "ishlamoq", "To do a job.", "She works in an office."],
    ["A1", "team", "jamoa", "A group of people working together.", "Our team meets every Monday."],
    ["A1", "boss", "boshliq", "A person in charge of employees.", "My boss is very supportive."],
    ["A2", "employee", "xodim", "A person who works for a company.", "The employee received a bonus."],
    ["A2", "manager", "menejer", "A person who oversees a team or department.", "The manager approved the request."],
    ["A2", "salary", "maosh", "Regular payment for work done.", "Her salary increased this year."],
    ["A2", "contract", "shartnoma", "A formal agreement about employment terms.", "He signed a two-year contract."],
    ["A2", "training", "o'qitish", "Instruction to develop skills for a job.", "New staff receive training in the first week."],
    ["B1", "recruitment", "yollash", "The process of finding and hiring new employees.", "Recruitment takes about a month."],
    ["B1", "performance review", "faoliyatni baholash", "A formal assessment of an employee's work.", "Her performance review was positive."],
    ["B1", "benefits", "imtiyozlar", "Extra advantages given to employees beyond salary.", "Health insurance is one of the benefits."],
    ["B1", "promotion", "lavozim ko'tarilishi", "An advancement to a higher position.", "He received a promotion last month."],
    ["B1", "resignation", "iste'foga chiqish", "The act of formally leaving a job.", "She submitted her resignation letter."],
    ["B2", "onboarding", "moslashuv jarayoni", "The process of integrating a new employee into a company.", "The onboarding program lasts two weeks."],
    ["B2", "employee retention", "xodimlarni ushlab qolish", "Keeping employees from leaving the company.", "Good benefits improve employee retention."],
    ["B2", "workplace diversity", "ish joyidagi xilma-xillik", "The inclusion of people from different backgrounds.", "The company values workplace diversity."],
    ["B2", "disciplinary action", "intizomiy chora", "A formal response to an employee's misconduct.", "He faced disciplinary action for lateness."],
    ["B2", "grievance", "shikoyat", "A formal complaint by an employee.", "She filed a grievance against her supervisor."],
    ["C1", "succession planning", "vorislik rejasi", "Planning who will take over key roles in the future.", "Succession planning ensures leadership continuity."],
    ["C1", "talent management", "iqtidorni boshqarish", "Strategies to attract, develop, and retain skilled staff.", "Talent management is a top HR priority."],
    ["C1", "attrition rate", "xodimlar yo'qotish darajasi", "The rate at which employees leave a company.", "The attrition rate dropped this quarter."],
    ["C1", "employee engagement", "xodimlar faolligi", "The level of enthusiasm employees have for their work.", "Surveys measure employee engagement annually."],
    ["C1", "exit interview", "ishdan ketish suhbati", "A discussion held when an employee leaves the company.", "The exit interview revealed useful feedback."],
    ["C2", "organizational culture", "tashkiliy madaniyat", "The shared values and behaviors within a company.", "Strong organizational culture boosts retention."],
    ["C2", "meritocracy", "meritokratiya", "A system where advancement is based on ability.", "The company prides itself on being a meritocracy."],
    ["C2", "workforce analytics", "ish kuchi tahlili", "Using data to make decisions about employees.", "Workforce analytics identified skill gaps."],
    ["C2", "constructive dismissal", "majburiy ishdan bo'shatish", "When an employee resigns due to intolerable conditions.", "The case was ruled a constructive dismissal."],
    ["C2", "psychological contract", "psixologik shartnoma", "The unwritten expectations between employer and employee.", "The psychological contract was broken by the layoffs."],
  ],
  management: [
    ["A1", "boss", "boshliq", "A person in charge of employees.", "My boss is kind."],
    ["A1", "lead", "boshqarmoq", "To be in charge of a group or task.", "She will lead the project."],
    ["A1", "team", "jamoa", "A group working together.", "The team worked hard."],
    ["A1", "plan", "reja", "A set of decisions about how to do something.", "We have a plan for next month."],
    ["A1", "decide", "qaror qabul qilmoq", "To choose something after thinking.", "We need to decide today."],
    ["A2", "manage", "boshqarmoq", "To be responsible for controlling something.", "He manages a small team."],
    ["A2", "organize", "tashkil qilmoq", "To arrange things in an orderly way.", "She organized the event well."],
    ["A2", "responsibility", "mas'uliyat", "A duty to deal with something.", "It's his responsibility to check the reports."],
    ["A2", "delegate", "vazifa topshirmoq", "To give a task to someone else.", "She delegated the task to her assistant."],
    ["A2", "goal", "maqsad", "Something a person or team aims to achieve.", "Our goal is to increase sales."],
    ["B1", "leadership style", "rahbarlik uslubi", "The way a person leads a team.", "His leadership style is very supportive."],
    ["B1", "motivate", "rag'batlantirmoq", "To encourage someone to act.", "Good managers know how to motivate staff."],
    ["B1", "supervise", "nazorat qilmoq", "To oversee and direct work.", "She supervises the sales team."],
    ["B1", "teamwork", "jamoaviy ish", "The combined effort of a group working together.", "Success depended on strong teamwork."],
    ["B1", "feedback", "fikr-mulohaza", "Comments about performance meant to guide improvement.", "He gave constructive feedback to his team."],
    ["B2", "micromanage", "mayda-chuyda nazorat qilish", "To control every small detail of a task closely.", "He tends to micromanage his employees."],
    ["B2", "empower", "vakolat bermoq", "To give someone authority or confidence to act.", "The manager empowered her team to make decisions."],
    ["B2", "accountability", "javobgarlik", "Being responsible for one's actions and their outcomes.", "Accountability is central to good leadership."],
    ["B2", "chain of command", "boshqaruv zanjiri", "The hierarchy of authority within an organization.", "Follow the chain of command for approvals."],
    ["B2", "strategic vision", "strategik ko'rish qobiliyati", "A clear long-term direction for an organization.", "The CEO shared his strategic vision."],
    ["C1", "transformational leadership", "transformatsion rahbarlik", "A style that inspires and motivates significant change.", "Transformational leadership drove the company's growth."],
    ["C1", "delegation of authority", "vakolatni topshirish", "Passing decision-making power to subordinates.", "Delegation of authority speeds up operations."],
    ["C1", "organizational hierarchy", "tashkiliy ierarxiya", "The structure of levels of authority in a company.", "The organizational hierarchy has five levels."],
    ["C1", "change management", "o'zgarishlarni boshqarish", "The process of managing transitions within an organization.", "Change management eased the merger process."],
    ["C1", "mentorship", "murabbiylik", "Guidance provided by an experienced person to a less experienced one.", "Mentorship helped her grow professionally."],
    ["C2", "servant leadership", "xizmatkor rahbarlik", "A style that prioritizes serving the team's needs first.", "Servant leadership improved staff morale."],
    ["C2", "laissez-faire management", "erkin boshqaruv uslubi", "A hands-off management style allowing autonomy.", "Laissez-faire management works well with experienced teams."],
    ["C2", "span of control", "boshqaruv doirasi", "The number of subordinates a manager oversees directly.", "Her span of control includes twelve employees."],
    ["C2", "executive presence", "yetakchilik nufuzi", "The quality of commanding confidence and respect as a leader.", "He is known for his strong executive presence."],
    ["C2", "succession pipeline", "vorislik zaxirasi", "A prepared group of candidates for future leadership roles.", "The succession pipeline ensures smooth transitions."],
  ],
  customer_service: [
    ["A1", "help", "yordam", "Assistance given to someone.", "Can I help you?"],
    ["A1", "customer", "mijoz", "A person who buys goods or services.", "The customer waited in line."],
    ["A1", "problem", "muammo", "A difficulty that needs to be solved.", "We have a problem with the order."],
    ["A1", "service", "xizmat", "Assistance or work provided to customers.", "The service here is excellent."],
    ["A1", "phone", "telefon", "A device used for calling.", "Please call us by phone."],
    ["A2", "complaint", "shikoyat", "A statement expressing dissatisfaction.", "She filed a complaint about the delay."],
    ["A2", "support", "qo'llab-quvvatlash", "Help provided, especially technical or customer help.", "Contact support if you have issues."],
    ["A2", "refund", "pulni qaytarish", "Money given back for a returned product.", "He asked for a refund."],
    ["A2", "satisfied", "qoniqqan", "Pleased with something.", "The customer was satisfied with the response."],
    ["A2", "solve", "hal qilmoq", "To find an answer to a problem.", "We solved the issue quickly."],
    ["B1", "customer satisfaction", "mijozlar qoniqishi", "How happy customers are with a product or service.", "Customer satisfaction improved this quarter."],
    ["B1", "helpdesk", "yordam xizmati", "A service that provides support to customers.", "Contact the helpdesk for technical issues."],
    ["B1", "feedback", "fikr-mulohaza", "Information about customer opinions used to improve service.", "We collect feedback after every purchase."],
    ["B1", "resolve", "hal qilmoq", "To successfully settle an issue.", "The agent resolved the complaint quickly."],
    ["B1", "follow up", "kuzatib bormoq", "To check on a previous issue or request.", "We'll follow up in two days."],
    ["B2", "escalation", "yuqori darajaga o'tkazish", "Passing an unresolved issue to a higher authority.", "The case required escalation to a supervisor."],
    ["B2", "service level agreement", "xizmat darajasi shartnomasi", "A contract defining the expected level of service.", "The SLA guarantees a 24-hour response time."],
    ["B2", "loyalty program", "sodiqlik dasturi", "A scheme rewarding repeat customers.", "Members earn points in the loyalty program."],
    ["B2", "first-call resolution", "birinchi qo'ng'iroqda hal qilish", "Solving a customer's issue during the first contact.", "First-call resolution improves customer trust."],
    ["B2", "empathy", "hamdardlik", "Understanding and sharing the feelings of the customer.", "Empathy is key in handling complaints."],
    ["C1", "customer retention", "mijozlarni ushlab qolish", "Keeping customers loyal over time.", "Good service boosts customer retention."],
    ["C1", "net promoter score", "sof tavsiya ko'rsatkichi", "A metric measuring customer loyalty and satisfaction.", "The company tracks its net promoter score monthly."],
    ["C1", "proactive support", "faol yordam", "Anticipating and resolving issues before customers report them.", "Proactive support reduced complaint volume."],
    ["C1", "churn", "mijozlar yo'qotilishi", "The loss of customers over a period of time.", "High churn signaled a service problem."],
    ["C1", "service recovery", "xizmatni tiklash", "Actions taken to fix a failed service experience.", "Service recovery turned an angry customer into a loyal one."],
    ["C2", "customer-centricity", "mijozga yo'naltirilganlik", "Placing the customer at the center of business decisions.", "Customer-centricity shapes every product decision."],
    ["C2", "omnichannel support", "ko'p kanalli yordam", "Consistent support across multiple platforms.", "Omnichannel support connects chat, phone, and email."],
    ["C2", "sentiment analysis", "hissiyot tahlili", "Analyzing customer opinions from text data.", "Sentiment analysis revealed rising frustration."],
    ["C2", "brand advocacy", "brendni himoya qilish", "Customers actively promoting a brand to others.", "Strong service turned customers into brand advocates."],
    ["C2", "service excellence", "xizmat mukammalligi", "Consistently outstanding customer service.", "The award recognized their service excellence."],
  ],
  business_travel: [
    ["A1", "trip", "safar", "A journey to a place and back.", "The trip lasted three days."],
    ["A1", "flight", "parvoz", "A journey by airplane.", "Our flight leaves at 6 AM."],
    ["A1", "hotel", "mehmonxona", "A place to stay while traveling.", "We booked a hotel near the airport."],
    ["A1", "luggage", "yuk (sayohat)", "Bags used for carrying belongings while traveling.", "Please check your luggage weight."],
    ["A1", "ticket", "chipta", "A document allowing travel.", "I bought a train ticket."],
    ["A2", "book", "bron qilmoq", "To reserve something in advance.", "She booked a flight to London."],
    ["A2", "itinerary", "sayohat rejasi", "A planned schedule of a journey.", "Here is your travel itinerary."],
    ["A2", "passport", "pasport", "An official document for international travel.", "Don't forget your passport."],
    ["A2", "check-in", "ro'yxatdan o'tish", "The process of registering for a flight or hotel.", "Check-in starts two hours before the flight."],
    ["A2", "delay", "kechikish", "A period of time when something is late.", "The flight had a two-hour delay."],
    ["B1", "business class", "biznes klass", "A premium level of air travel.", "He always flies business class."],
    ["B1", "layover", "oraliq to'xtash", "A stop between flights during a journey.", "We had a three-hour layover in Dubai."],
    ["B1", "expense report", "xarajatlar hisoboti", "A document listing costs incurred during a trip.", "Submit your expense report by Friday."],
    ["B1", "boarding pass", "chiqish qog'ozi", "A document allowing you to board a flight.", "Show your boarding pass at the gate."],
    ["B1", "reservation", "bron", "An arrangement to secure something in advance.", "I made a hotel reservation."],
    ["B2", "per diem", "kunlik xarajat puli", "A fixed daily allowance for travel expenses.", "The per diem covers meals and transport."],
    ["B2", "visa requirement", "viza talabi", "The official conditions needed to enter a country.", "Check the visa requirement before booking."],
    ["B2", "connecting flight", "ulanuvchi parvoz", "A flight that connects to another to reach the final destination.", "We missed our connecting flight."],
    ["B2", "travel policy", "sayohat siyosati", "Company rules governing business travel.", "The travel policy limits hotel budgets."],
    ["B2", "jet lag", "vaqt farqidan charchash", "Tiredness caused by crossing time zones.", "He suffered from jet lag after the long flight."],
    ["C1", "corporate travel policy", "korporativ sayohat siyosati", "Formal company guidelines for business trips.", "The corporate travel policy was updated this year."],
    ["C1", "reimbursement claim", "xarajatlarni qoplash so'rovi", "A request for repayment of travel expenses.", "Submit your reimbursement claim within a week."],
    ["C1", "travel itinerary", "batafsil sayohat rejasi", "A detailed plan of a business trip's schedule.", "The travel itinerary included three client meetings."],
    ["C1", "duty of care", "g'amxo'rlik majburiyati", "An employer's obligation to ensure traveler safety.", "Duty of care requires tracking employee locations abroad."],
    ["C1", "frequent flyer", "doimiy uchuvchi", "A traveler who earns rewards for frequent flights.", "He is a frequent flyer with this airline."],
    ["C2", "travel risk management", "sayohat xavflarini boshqarish", "Strategies to reduce risks during business travel.", "Travel risk management includes emergency protocols."],
    ["C2", "cost containment", "xarajatlarni cheklash", "Strategies to control and reduce travel spending.", "Cost containment measures reduced the travel budget."],
    ["C2", "expense reconciliation", "xarajatlarni solishtirish", "Matching reported expenses with receipts and records.", "Expense reconciliation is done monthly."],
    ["C2", "travel authorization", "sayohatga ruxsat", "Formal approval required before a business trip.", "He needed travel authorization from his director."],
    ["C2", "incidental expenses", "qo'shimcha xarajatlar", "Small additional costs incurred during travel.", "Incidental expenses include tips and snacks."],
  ],
  networking: [
    ["A1", "friend", "do'st", "A person you know well and like.", "He met a new friend at work."],
    ["A1", "contact", "aloqa (shaxs)", "A person you know who can help professionally.", "She has many contacts in finance."],
    ["A1", "meet", "uchrashmoq", "To come together with someone.", "Let's meet after the conference."],
    ["A1", "talk", "gaplashmoq", "To speak with someone.", "We talked about the new project."],
    ["A1", "card", "vizit karta", "A small card with contact information.", "He gave me his card."],
    ["A2", "introduce", "tanishtirmoq", "To present someone to another person for the first time.", "Let me introduce you to my colleague."],
    ["A2", "connection", "aloqa", "A relationship with a person, often professional.", "She made a useful connection at the event."],
    ["A2", "event", "tadbir", "An organized occasion, such as a conference.", "The networking event starts at 6 PM."],
    ["A2", "exchange", "almashmoq", "To give and receive something mutually.", "They exchanged business cards."],
    ["A2", "colleague", "hamkasb", "A person you work with.", "My colleague introduced me to a client."],
    ["B1", "business card", "vizit karta", "A small card with professional contact details.", "Always carry business cards to events."],
    ["B1", "follow up", "kuzatib bormoq", "To maintain contact after an initial meeting.", "I'll follow up with an email tomorrow."],
    ["B1", "referral", "tavsiya (mijoz)", "A recommendation to another person or business.", "We got a new client through a referral."],
    ["B1", "mentor", "murabbiy", "An experienced person who guides someone less experienced.", "She found a mentor in her industry."],
    ["B1", "acquaintance", "tanish", "A person you know slightly, not a close friend.", "He is a business acquaintance, not a friend."],
    ["B2", "elevator pitch", "qisqa tanishtiruv nutqi", "A brief persuasive summary of who you are and what you do.", "She prepared a 30-second elevator pitch."],
    ["B2", "professional network", "kasbiy tarmoq", "A group of professional contacts and relationships.", "Building a professional network takes time."],
    ["B2", "rapport", "yaqin munosabat", "A friendly, mutual understanding with another person.", "He quickly built rapport with the client."],
    ["B2", "LinkedIn profile", "LinkedIn profili", "An online professional profile used for networking.", "Update your LinkedIn profile before the conference."],
    ["B2", "mutual connection", "umumiy aloqa", "A shared contact known by two people.", "We found we had a mutual connection."],
    ["C1", "strategic alliance", "strategik ittifoq", "A formal partnership between businesses for mutual benefit.", "The two companies formed a strategic alliance."],
    ["C1", "industry connections", "soha aloqalari", "Professional relationships within a specific field.", "His industry connections opened new doors."],
    ["C1", "relationship building", "munosabat qurish", "The ongoing process of developing professional ties.", "Relationship building is key to long-term sales."],
    ["C1", "cold outreach", "notanish shaxsga murojaat", "Contacting someone with no previous relationship.", "Cold outreach on LinkedIn led to a new deal."],
    ["C1", "thought leadership", "fikr yetakchiligi", "Being recognized as an expert voice in a field.", "He built thought leadership through articles."],
    ["C2", "social capital", "ijtimoiy kapital", "The value gained from social relationships and networks.", "Her social capital helped her career advance quickly."],
    ["C2", "reciprocal networking", "o'zaro tarmoq aloqasi", "Networking based on mutual benefit and exchange.", "Reciprocal networking strengthens long-term partnerships."],
    ["C2", "gatekeeper access", "darvozabon orqali kirish", "Gaining entry through a person who controls access.", "Gatekeeper access to executives is hard to earn."],
    ["C2", "weak ties", "zaif aloqalar", "Distant acquaintances that can offer new opportunities.", "Weak ties often lead to unexpected job offers."],
    ["C2", "professional ecosystem", "kasbiy ekotizim", "The interconnected network of people and organizations in a field.", "He is well-connected within the tech ecosystem."],
  ],
  startups: [
    ["A1", "idea", "g'oya", "A thought or plan for something new.", "She has a great idea for a business."],
    ["A1", "start", "boshlamoq", "To begin something.", "They start the company next year."],
    ["A1", "money", "pul", "Currency needed to run a business.", "They need money to grow."],
    ["A1", "business", "biznes", "A commercial activity or company.", "He runs a small business."],
    ["A1", "team", "jamoa", "A group working together toward a goal.", "The team has five members."],
    ["A2", "entrepreneur", "tadbirkor", "A person who starts and runs a business.", "She is a successful entrepreneur."],
    ["A2", "launch", "ishga tushirmoq", "To officially start a product or company.", "They launched the app last month."],
    ["A2", "investor", "investor", "A person who puts money into a business.", "An investor funded their startup."],
    ["A2", "risk", "xavf", "The possibility of loss or failure.", "Starting a business involves risk."],
    ["A2", "plan", "reja", "A detailed proposal for achieving something.", "They wrote a business plan."],
    ["B1", "startup", "startap", "A newly established, innovative company.", "The startup grew quickly."],
    ["B1", "funding", "moliyalashtirish", "Money provided for a project or business.", "They received funding from investors."],
    ["B1", "pitch", "taqdimot (investorlarga)", "A presentation aimed at persuading investors.", "Their pitch impressed the judges."],
    ["B1", "prototype", "prototip", "An early sample of a product used for testing.", "They built a working prototype."],
    ["B1", "growth", "o'sish", "An increase in size or success.", "The company saw rapid growth."],
    ["B2", "venture capital", "venchur kapital", "Investment provided to startups with high growth potential.", "They secured venture capital in the first round."],
    ["B2", "business model", "biznes modeli", "The plan for how a company creates and earns value.", "Their business model relies on subscriptions."],
    ["B2", "scalability", "kengaytirilishi mumkinligi", "The ability of a business to grow without major limits.", "Investors were impressed by the app's scalability."],
    ["B2", "bootstrap", "o'z mablag'i bilan boshlash", "To start a business without external funding.", "They bootstrapped the company for two years."],
    ["B2", "pivot", "yo'nalishni o'zgartirish", "To change a business strategy significantly.", "The startup had to pivot after low sales."],
    ["C1", "seed funding", "boshlang'ich investitsiya", "The first official money raised by a startup.", "They raised seed funding from angel investors."],
    ["C1", "equity stake", "kapital ulushi", "A percentage of ownership in a company.", "The investor received a 10% equity stake."],
    ["C1", "valuation", "baholash (kompaniya)", "The estimated worth of a company.", "The startup's valuation reached $10 million."],
    ["C1", "exit strategy", "chiqish strategiyasi", "A plan for how investors will eventually profit.", "Their exit strategy is an acquisition."],
    ["C1", "minimum viable product", "minimal ishlaydigan mahsulot", "A basic product version used to test the market.", "They launched a minimum viable product first."],
    ["C2", "unicorn", "unicorn kompaniya", "A startup valued at over one billion dollars.", "The company became a unicorn within five years."],
    ["C2", "disruptive innovation", "buzg'unchi innovatsiya", "An innovation that fundamentally changes an industry.", "Their technology was a disruptive innovation in logistics."],
    ["C2", "angel investor", "farishta investor", "A wealthy individual who funds early-stage startups.", "An angel investor backed their first round."],
    ["C2", "burn rate", "mablag' sarflanish tezligi", "The rate at which a startup spends its capital.", "Their burn rate was too high to sustain."],
    ["C2", "term sheet", "shartlar varag'i", "A document outlining the terms of an investment deal.", "They signed the term sheet after negotiations."],
  ],
  logistics: [
    ["A1", "truck", "yuk mashinasi", "A large vehicle for transporting goods.", "The truck delivered the goods on time."],
    ["A1", "ship", "kema", "A large boat used for transporting goods.", "The goods arrived by ship."],
    ["A1", "box", "quti", "A container used to hold or transport items.", "Put the items in the box."],
    ["A1", "deliver", "yetkazib bermoq", "To bring goods to a destination.", "They deliver every Tuesday."],
    ["A1", "warehouse", "ombor", "A building for storing goods.", "The goods are kept in a warehouse."],
    ["A2", "shipment", "yuk jo'natmasi", "A batch of goods sent together.", "The shipment arrived a day late."],
    ["A2", "order", "buyurtma", "A request for goods to be supplied.", "We placed a large order."],
    ["A2", "supplier", "yetkazib beruvchi", "A company that provides goods.", "Our supplier is based overseas."],
    ["A2", "transport", "tashish", "To move goods from one place to another.", "They transport goods by rail."],
    ["A2", "stock", "zaxira", "Goods available for sale or use.", "We're low on stock."],
    ["B1", "supply chain", "ta'minot zanjiri", "The full process from production to delivery.", "The supply chain was disrupted by the storm."],
    ["B1", "inventory", "inventar", "The full list or stock of goods held.", "They updated their inventory system."],
    ["B1", "distribution", "tarqatish", "The process of delivering goods to customers.", "Distribution costs rose this year."],
    ["B1", "freight", "yuk tashish", "Goods transported in bulk by truck, train, or ship.", "The freight was cleared through customs quickly."],
    ["B1", "customs", "bojxona", "The authority controlling goods entering a country.", "The shipment was held at customs."],
    ["B2", "logistics network", "logistika tarmog'i", "The system of routes and facilities for moving goods.", "They expanded their logistics network overseas."],
    ["B2", "lead time", "yetkazib berish muddati", "The time between ordering and receiving goods.", "The lead time for this part is two weeks."],
    ["B2", "bottleneck", "tor joy (jarayonda)", "A point causing delays in a process.", "The port was a major bottleneck in the supply chain."],
    ["B2", "procurement", "xarid qilish jarayoni", "The process of obtaining goods or services for a business.", "Procurement negotiated a better contract."],
    ["B2", "just-in-time", "aynan vaqtida yetkazish", "A system delivering goods exactly when needed.", "Just-in-time delivery reduces storage costs."],
    ["C1", "supply chain resilience", "ta'minot zanjiri chidamliligi", "The ability of a supply chain to withstand disruptions.", "Supply chain resilience improved after the crisis."],
    ["C1", "freight forwarding", "yuk tashishni tashkil qilish", "Arranging the shipment of goods on behalf of shippers.", "A freight forwarder handled all the paperwork."],
    ["C1", "inventory turnover", "inventar aylanish tezligi", "How often stock is sold and replaced over a period.", "High inventory turnover indicates strong sales."],
    ["C1", "backorder", "kechiktirilgan buyurtma", "An order that cannot be filled immediately due to stock shortage.", "The item is on backorder until next month."],
    ["C1", "third-party logistics", "uchinchi tomon logistikasi", "Outsourcing logistics operations to an external company.", "They use third-party logistics for warehousing."],
    ["C2", "supply chain optimization", "ta'minot zanjirini optimallashtirish", "Improving efficiency across the entire supply chain.", "Supply chain optimization cut delivery times in half."],
    ["C2", "demand forecasting", "talabni bashorat qilish", "Predicting future customer demand for products.", "Demand forecasting relies on historical sales data."],
    ["C2", "vendor-managed inventory", "sotuvchi tomonidan boshqariladigan zaxira", "A system where the supplier manages the buyer's stock levels.", "Vendor-managed inventory reduced stockouts."],
    ["C2", "reverse logistics", "teskari logistika", "The process of managing returned goods.", "Reverse logistics handles product returns efficiently."],
    ["C2", "bullwhip effect", "bullwhip effekti", "Increasing demand fluctuations moving up the supply chain.", "The bullwhip effect caused excess inventory upstream."],
  ],
  technology: [
    ["A1", "computer", "kompyuter", "An electronic device for processing data.", "I use my computer for work."],
    ["A1", "internet", "internet", "A global network connecting computers.", "We need a strong internet connection."],
    ["A1", "app", "ilova", "A software program, especially for mobile devices.", "This app helps track expenses."],
    ["A1", "phone", "telefon", "A device used for communication.", "My phone battery is low."],
    ["A1", "data", "ma'lumot", "Information stored or processed by a computer.", "The data is saved automatically."],
    ["A2", "software", "dasturiy ta'minot", "Programs that run on a computer.", "We installed new software."],
    ["A2", "update", "yangilash", "A newer version of software or information.", "Please install the latest update."],
    ["A2", "password", "parol", "A secret word used to access an account.", "Choose a strong password."],
    ["A2", "device", "qurilma", "An electronic tool or gadget.", "This device connects to WiFi."],
    ["A2", "online", "onlayn", "Connected to the internet.", "The meeting is online today."],
    ["B1", "cybersecurity", "kiberxavfsizlik", "Protection of computer systems from digital attacks.", "Cybersecurity is a growing concern for companies."],
    ["B1", "cloud storage", "bulutli xotira", "Online space used to store data remotely.", "We back up files to cloud storage."],
    ["B1", "database", "ma'lumotlar bazasi", "An organized collection of stored data.", "The database holds all customer records."],
    ["B1", "network", "tarmoq", "A system of connected computers or devices.", "The office network was down this morning."],
    ["B1", "upgrade", "yangilash (tizim)", "To improve a system to a better version.", "They upgraded their servers last year."],
    ["B2", "artificial intelligence", "sun'iy intellekt", "Technology that enables machines to simulate human intelligence.", "Artificial intelligence powers the chatbot."],
    ["B2", "automation", "avtomatlashtirish", "Using technology to perform tasks without human effort.", "Automation reduced manual work significantly."],
    ["B2", "data breach", "ma'lumotlar sizib chiqishi", "An incident where protected data is accessed illegally.", "The company reported a major data breach."],
    ["B2", "user interface", "foydalanuvchi interfeysi", "The visual part of software users interact with.", "The new user interface is more intuitive."],
    ["B2", "digital transformation", "raqamli transformatsiya", "The integration of digital technology into all business areas.", "Digital transformation changed how they operate."],
    ["C1", "machine learning", "mashinali o'rganish", "A type of AI that learns patterns from data.", "Machine learning improves product recommendations."],
    ["C1", "scalable infrastructure", "kengaytiriladigan infratuzilma", "IT systems designed to grow with demand.", "Scalable infrastructure supported rapid user growth."],
    ["C1", "encryption protocol", "shifrlash protokoli", "A method of securing data through coding.", "They use a strong encryption protocol for payments."],
    ["C1", "system integration", "tizimlarni birlashtirish", "Connecting different IT systems to work together.", "System integration took several months."],
    ["C1", "tech stack", "texnologik stek", "The set of technologies used to build a product.", "Their tech stack includes React and Node.js."],
    ["C2", "algorithmic bias", "algoritmik noaniqlik", "Unfair outcomes caused by flawed data or design in algorithms.", "The team addressed algorithmic bias in the model."],
    ["C2", "edge computing", "chekka hisoblash", "Processing data closer to where it is generated.", "Edge computing reduces latency for IoT devices."],
    ["C2", "technical debt", "texnik qarz", "The future cost of choosing a quick, imperfect solution now.", "Technical debt slowed down new feature development."],
    ["C2", "API ecosystem", "API ekotizimi", "The network of connected services built around an API.", "Their API ecosystem attracts external developers."],
    ["C2", "quantum computing", "kvant hisoblash", "Computing using quantum mechanics for vastly faster processing.", "Quantum computing could revolutionize encryption."],
  ],
  project_management: [
    ["A1", "plan", "reja", "A detailed proposal for achieving something.", "We made a plan for the project."],
    ["A1", "task", "vazifa", "A piece of work to be done.", "Each task has an owner."],
    ["A1", "team", "jamoa", "A group of people working together.", "The team meets weekly."],
    ["A1", "time", "vaqt", "The measured period during which an action occurs.", "We don't have much time left."],
    ["A1", "goal", "maqsad", "The desired result of a project.", "Our goal is to finish by June."],
    ["A2", "project", "loyiha", "A planned piece of work with a specific goal.", "The project starts next week."],
    ["A2", "deadline", "muddat", "The latest time by which something must be finished.", "The deadline is Friday."],
    ["A2", "schedule", "jadval", "A plan showing when tasks will happen.", "Check the project schedule."],
    ["A2", "progress", "rivojlanish", "Movement toward a goal.", "The team made good progress this week."],
    ["A2", "budget", "byudjet", "The planned amount of money for a project.", "Stay within the project budget."],
    ["B1", "milestone", "muhim bosqich", "An important stage or event in a project.", "We reached an important milestone."],
    ["B1", "timeline", "vaqt jadvali", "A visual plan showing when tasks will occur.", "The timeline shows all key dates."],
    ["B1", "resource", "resurs", "People, money, or materials needed for a project.", "We need more resources for this phase."],
    ["B1", "risk", "xavf", "A possible problem that could affect the project.", "We identified several project risks."],
    ["B1", "deliverable", "topshiriladigan natija", "A specific output produced during a project.", "The first deliverable is due next month."],
    ["B2", "scope creep", "doiraning kengayib ketishi", "The gradual expansion of a project beyond its original goals.", "Scope creep delayed the launch."],
    ["B2", "stakeholder management", "manfaatdor tomonlarni boshqarish", "Handling the interests and expectations of stakeholders.", "Good stakeholder management prevented conflicts."],
    ["B2", "Gantt chart", "Gantt diagrammasi", "A chart showing a project schedule over time.", "The Gantt chart outlines all tasks and deadlines."],
    ["B2", "critical path", "kritik yo'l", "The sequence of tasks that determines the project's minimum duration.", "Any delay on the critical path affects the deadline."],
    ["B2", "project charter", "loyiha nizomi", "A document formally authorizing a project.", "The project charter defines the objectives and scope."],
    ["C1", "agile methodology", "agile metodologiyasi", "A flexible, iterative approach to project management.", "The team adopted agile methodology for faster delivery."],
    ["C1", "sprint planning", "sprint rejalashtirish", "A meeting to plan work for the next work cycle.", "Sprint planning happens every two weeks."],
    ["C1", "risk mitigation", "xavfni kamaytirish", "Actions taken to reduce the impact of potential risks.", "Risk mitigation plans were prepared in advance."],
    ["C1", "project governance", "loyiha boshqaruv tizimi", "The framework of rules and processes guiding a project.", "Project governance ensured accountability."],
    ["C1", "change request", "o'zgartirish so'rovi", "A formal proposal to modify project scope or plans.", "The client submitted a change request."],
    ["C2", "earned value management", "olingan qiymatni boshqarish", "A method for measuring project performance and progress.", "Earned value management tracked cost efficiency."],
    ["C2", "portfolio management", "portfel boshqaruvi", "Managing multiple projects to achieve strategic goals.", "Portfolio management balanced resources across projects."],
    ["C2", "dependency mapping", "bog'liqliklarni xaritalash", "Identifying how tasks depend on one another.", "Dependency mapping revealed a scheduling conflict."],
    ["C2", "resource leveling", "resurslarni tekislash", "Adjusting a schedule to balance resource use.", "Resource leveling prevented team burnout."],
    ["C2", "project closure", "loyihani yakunlash", "The formal completion and review of a project.", "Project closure includes a final performance review."],
  ],
  legal: [
    ["A1", "rule", "qoida", "A statement guiding behavior or action.", "Follow the company rules."],
    ["A1", "law", "qonun", "A system of official rules.", "It's against the law."],
    ["A1", "sign", "imzo qo'ymoq", "To write your name to approve a document.", "Please sign here."],
    ["A1", "agree", "kelishmoq", "To accept the same terms.", "Both parties agree."],
    ["A1", "paper", "qog'oz (hujjat)", "A document, often official.", "Bring the paper to the office."],
    ["A2", "contract", "shartnoma", "A written legal agreement.", "They signed the contract."],
    ["A2", "agreement", "kelishuv", "A decision reached by two or more parties.", "The agreement was fair to both sides."],
    ["A2", "rights", "huquqlar", "Legal entitlements a person has.", "Employees have certain legal rights."],
    ["A2", "legal", "huquqiy", "Relating to the law.", "It's important to seek legal advice."],
    ["A2", "document", "hujjat", "A written or printed piece of information.", "Please review this document."],
    ["B1", "clause", "band (shartnomada)", "A specific section of a legal document.", "Check the payment clause carefully."],
    ["B1", "terms and conditions", "shartlar va qoidalar", "The rules governing an agreement.", "Read the terms and conditions before signing."],
    ["B1", "liability", "javobgarlik (huquqiy)", "Legal responsibility for something.", "The company accepted liability for the damage."],
    ["B1", "breach", "shartnomani buzish", "A failure to follow the terms of an agreement.", "The breach of contract led to a lawsuit."],
    ["B1", "dispute", "nizo", "A disagreement or conflict between parties.", "The dispute was settled out of court."],
    ["B2", "confidentiality agreement", "maxfiylik shartnomasi", "A contract protecting private business information.", "Employees signed a confidentiality agreement."],
    ["B2", "intellectual property", "intellektual mulk", "Legal rights over creations of the mind.", "The patent protects their intellectual property."],
    ["B2", "arbitration", "arbitraj", "Resolving a dispute outside of court by a neutral party.", "The contract requires arbitration for disputes."],
    ["B2", "jurisdiction", "yurisdiksiya", "The official power to make legal decisions in an area.", "The case falls under a different jurisdiction."],
    ["B2", "indemnity", "kompensatsiya kafolati", "Protection against financial loss or legal responsibility.", "The clause provides indemnity for damages."],
    ["C1", "force majeure", "fors-major", "Unforeseeable events that prevent contract fulfillment.", "The pandemic was declared a force majeure event."],
    ["C1", "non-disclosure agreement", "maxfiylik to'g'risidagi shartnoma", "A legal contract preventing the sharing of confidential information.", "They signed an NDA before discussing the deal."],
    ["C1", "litigation", "sud jarayoni", "The process of taking legal action in court.", "The dispute escalated into litigation."],
    ["C1", "statute of limitations", "da'vo muddati", "The legal time limit for taking legal action.", "The statute of limitations had already expired."],
    ["C1", "due diligence", "har tomonlama tekshiruv", "A careful investigation before making a business decision.", "Due diligence revealed hidden financial risks."],
    ["C2", "fiduciary duty", "ishonchli majburiyat", "A legal obligation to act in another's best interest.", "Directors owe a fiduciary duty to shareholders."],
    ["C2", "tortious liability", "delikt javobgarligi", "Legal responsibility for causing harm through wrongdoing.", "The company faced tortious liability for negligence."],
    ["C2", "injunctive relief", "cheklovchi sud qarori", "A court order requiring a party to stop an action.", "The court granted injunctive relief immediately."],
    ["C2", "contractual indemnification", "shartnomaviy kompensatsiya", "A contractual promise to cover another's losses.", "The clause included full contractual indemnification."],
    ["C2", "regulatory compliance", "qonunchilikka muvofiqlik", "Adherence to laws and regulations governing an industry.", "Regulatory compliance is audited annually."],
  ],
  strategy: [
    ["A1", "plan", "reja", "A method for achieving a goal.", "They made a plan for the year."],
    ["A1", "goal", "maqsad", "Something a person or company wants to achieve.", "Our goal is to grow."],
    ["A1", "idea", "g'oya", "A thought or suggestion.", "She had a good idea."],
    ["A1", "future", "kelajak", "The time that is yet to come.", "They are planning for the future."],
    ["A1", "choice", "tanlov", "A decision between options.", "We have two choices."],
    ["A2", "strategy", "strategiya", "A plan for achieving a long-term goal.", "Their strategy focused on new markets."],
    ["A2", "target", "maqsad ko'rsatkichi", "A specific goal to be achieved.", "They set a sales target."],
    ["A2", "decision", "qaror", "A choice made after consideration.", "It was a difficult decision."],
    ["A2", "growth", "o'sish", "An increase in size or success.", "The company focuses on growth."],
    ["A2", "market", "bozor", "The group of people who may buy a product.", "They entered a new market."],
    ["B1", "strategic plan", "strategik reja", "A long-term plan outlining goals and actions.", "The strategic plan covers the next five years."],
    ["B1", "competitive advantage", "raqobat ustunligi", "A factor that gives a company an edge over rivals.", "Their technology gives them a competitive advantage."],
    ["B1", "mission statement", "missiya bayonoti", "A short statement of a company's core purpose.", "The mission statement guides all decisions."],
    ["B1", "SWOT analysis", "SWOT tahlili", "An analysis of strengths, weaknesses, opportunities, and threats.", "They conducted a SWOT analysis before expanding."],
    ["B1", "objective", "vazifa/maqsad", "A specific result a plan is intended to achieve.", "Each department has clear objectives."],
    ["B2", "market positioning", "bozordagi o'rin", "How a brand is perceived compared to competitors.", "Their market positioning emphasizes quality."],
    ["B2", "long-term vision", "uzoq muddatli qarash", "A clear picture of desired future outcomes.", "The CEO shared a long-term vision for the firm."],
    ["B2", "strategic partnership", "strategik hamkorlik", "A formal cooperation between organizations for mutual benefit.", "They formed a strategic partnership with a supplier."],
    ["B2", "diversification", "diversifikatsiya", "Expanding into new products or markets to reduce risk.", "Diversification protected the fund during the downturn."],
    ["B2", "benchmarking", "solishtirma tahlil", "Comparing performance against industry standards or competitors.", "Benchmarking helped identify performance gaps."],
    ["C1", "competitive intelligence", "raqobat razvedkasi", "Information gathered about competitors to inform strategy.", "Competitive intelligence shaped their pricing strategy."],
    ["C1", "strategic alignment", "strategik moslashuv", "Ensuring all parts of an organization work toward the same goals.", "Strategic alignment improved cross-team efficiency."],
    ["C1", "core competency", "asosiy kompetensiya", "A key strength that gives a company its advantage.", "Innovation is their core competency."],
    ["C1", "value proposition", "qiymat taklifi", "The unique benefit a product offers to customers.", "Their value proposition is speed and reliability."],
    ["C1", "blue ocean strategy", "ko'k okean strategiyasi", "A strategy of creating uncontested new markets.", "They pursued a blue ocean strategy in wellness tech."],
    ["C2", "strategic pivot", "strategik burilish", "A major change in a company's direction or strategy.", "The strategic pivot saved the company from decline."],
    ["C2", "disruptive strategy", "buzg'unchi strategiya", "A strategy that fundamentally changes an industry.", "Their disruptive strategy reshaped the market."],
    ["C2", "first-mover advantage", "birinchi bo'lish afzalligi", "The benefit gained by entering a market first.", "First-mover advantage helped them dominate early."],
    ["C2", "portfolio diversification", "portfelni diversifikatsiyalash", "Spreading business investments to reduce overall risk.", "Portfolio diversification balanced their revenue streams."],
    ["C2", "scenario planning", "stsenariy rejalashtirish", "Preparing strategies for multiple possible futures.", "Scenario planning prepared them for market shifts."],
  ],
  workplace_culture: [
    ["A1", "office", "ofis", "A place where people work, especially with desks.", "The office is on the third floor."],
    ["A1", "desk", "stol", "A piece of furniture for working at.", "My desk is near the window."],
    ["A1", "work", "ish", "Activity involving effort done to achieve a result.", "We start work at nine."],
    ["A1", "rule", "qoida", "A statement guiding acceptable behavior.", "Follow the office rules."],
    ["A1", "team", "jamoa", "A group of people working together.", "Our team is friendly."],
    ["A2", "workplace", "ish joyi", "The place where a person works.", "The workplace is very modern."],
    ["A2", "colleague", "hamkasb", "A person you work with.", "My colleague is helpful."],
    ["A2", "dress code", "kiyinish qoidasi", "Rules about appropriate clothing at work.", "The dress code is business casual."],
    ["A2", "break", "tanaffus", "A short pause from work.", "We take a break at noon."],
    ["A2", "schedule", "jadval", "A plan of work hours or tasks.", "Check your work schedule."],
    ["B1", "work-life balance", "ish va shaxsiy hayot muvozanati", "A healthy balance between job and personal life.", "The company promotes work-life balance."],
    ["B1", "company culture", "kompaniya madaniyati", "The shared values and behaviors within a company.", "Company culture affects employee happiness."],
    ["B1", "teamwork", "jamoaviy ish", "Working effectively together as a group.", "Teamwork led to the project's success."],
    ["B1", "punctuality", "vaqtga rioya qilish", "Being on time.", "Punctuality is expected at meetings."],
    ["B1", "professionalism", "professionallik", "Behaving in a competent, respectful manner at work.", "She showed great professionalism under pressure."],
    ["B2", "workplace diversity", "ish joyidagi xilma-xillik", "The inclusion of people from different backgrounds.", "Workplace diversity strengthens creativity."],
    ["B2", "remote work", "masofaviy ish", "Working from a location outside the traditional office.", "Remote work became common after the pandemic."],
    ["B2", "corporate values", "korporativ qadriyatlar", "The core principles guiding a company's behavior.", "Honesty is one of our corporate values."],
    ["B2", "employee morale", "xodimlar ruhiyati", "The overall satisfaction and attitude of employees.", "Team events improved employee morale."],
    ["B2", "open-door policy", "ochiq eshik siyosati", "A policy allowing employees easy access to management.", "The manager follows an open-door policy."],
    ["C1", "organizational culture", "tashkiliy madaniyat", "The shared values and norms shaping an organization.", "Strong organizational culture boosts retention."],
    ["C1", "psychological safety", "psixologik xavfsizlik", "A climate where people feel safe to speak up.", "Psychological safety encourages honest feedback."],
    ["C1", "inclusive workplace", "inklyuziv ish joyi", "A work environment that values and includes everyone.", "They built an inclusive workplace for all employees."],
    ["C1", "hybrid work model", "gibrid ish modeli", "A system combining remote and in-office work.", "The hybrid work model gives employees flexibility."],
    ["C1", "employee well-being", "xodimlar farovonligi", "The overall physical and mental health of employees.", "Employee well-being programs reduced burnout."],
    ["C2", "cultural fit", "madaniy moslik", "How well a person's values align with a company's culture.", "Cultural fit is assessed during interviews."],
    ["C2", "tacit norms", "aytilmagan me'yorlar", "Unwritten but understood rules of behavior in a workplace.", "New hires quickly learn the tacit norms."],
    ["C2", "groupthink", "guruh fikri", "The tendency to conform to group opinion without critical thinking.", "Groupthink led to a poor strategic decision."],
    ["C2", "institutional inertia", "institutsional inersiya", "Resistance to change within an established organization.", "Institutional inertia slowed the digital transformation."],
    ["C2", "cultural transformation", "madaniy transformatsiya", "A deliberate shift in an organization's values and behaviors.", "Cultural transformation was key to the merger's success."],
  ],
};

export const VOCAB_WORDS = Object.entries(RAW).flatMap(([topicId, rows]) =>
  rows.map(([level, term, translation, def, example], i) => ({
    id: `${topicId}-${i + 1}`,
    topicId,
    level,
    term,
    translation,
    def,
    example,
  }))
);
